site_name: NurseNotes Documentation
site_url: https://CanelaSoftware.github.io/NN_Documentation
repo_url: https://github.com/CanelaSoftware/NN_Documentation
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    primary: light green
    accent: light green
  logo: assets/nn-icon.png
  favicon: assets/nn-icon.png
  features:
    - content.action.edit
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - tables
  - attr_list
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 3

nav:
  - Introduction:
      - Introduction: index.md
#       - What's Included: introduction/what-is-included.md
      - Getting Started: introduction/getting-started.md
  - Vision Screening: 
      - Starting a Vision Test: vision-screening/vision-screening.md
      - How To Vision Screen: vision-screening/how-to-vision-screen.md
      - Vision Results: vision-screening/vision-results.md
      - Manual Vision Screening: vision-screening/manual-vision-screening.md
      - PhotoScreener Integration: vision-screening/photoscreener-integration.md
  - Audiometry Screening: 
      - Audiometry Hardware: audiometry-screening/audiometry-hardware.md
      - Starting a Hearing Screen: audiometry-screening/starting-a-hearing-screen.md
      - How To Screen Hearing: audiometry-screening/how-to-screen-hearing.md
  - Other Screenings and  Documentation:
    - Physicals: other-screenings/physicals.md
    - Dental: other-screenings/dental.md
    - RN Notes and Treatments: other-screenings/rn-notes-and-treatments.md
    - Assessment: other-screenings/assessment.md
    - Documents: other-screenings/documents.md
  - Printing Documents:
    - Print Center: printing-documents/print-center.md
    - Other Printing: printing-documents/other-printing.md
  - Analytics, Status, Accounts, and Settings:
    - Analytics: analytics-status-accounts-settings/analytics.md
    - Account: analytics-status-accounts-settings/account.md
    - Settings: analytics-status-accounts-settings/settings.md
#   - Hotkeys:
copyright: Copyright &copy; Canela Software
extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/27A3eTAG
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/canela-software-inc/
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/appli-io.bsky.social
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/appli_io/
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search
